# Generated by Django 3.0.8 on 2020-10-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('direction', models.CharField(max_length=150, verbose_name='Direction')),
                ('hostname', models.CharField(max_length=50, verbose_name='Hostanme')),
                ('nuuma', models.CharField(max_length=70, verbose_name='Nuuma')),
                ('serial_number', models.CharField(max_length=50, verbose_name='Serial number')),
                ('product_number', models.CharField(blank=True, max_length=50, verbose_name='Product number')),
                ('mac_address', models.CharField(max_length=50, verbose_name='MAC')),
                ('mac_wifi', models.CharField(blank=True, max_length=50, verbose_name='MAC WIFI')),
                ('manufacturer', models.CharField(max_length=50, verbose_name='Manufacturer')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('model', models.CharField(choices=[('0', 'Portatil'), ('1', 'Sobremesa'), ('2', 'Surface')], max_length=5, verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Inventory',
                'ordering': ['nuuma'],
            },
        ),
    ]
