# Generated by Django 3.0.8 on 2020-10-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20201013_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='observations',
            field=models.CharField(default=1, max_length=70, verbose_name='Observations'),
            preserve_default=False,
        ),
    ]
