# Generated by Django 3.0.8 on 2020-10-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventory_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='warranty',
            field=models.CharField(blank=True, max_length=50, verbose_name='Warranty'),
        ),
    ]
