# Generated by Django 3.0.8 on 2020-10-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventory_warranty'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracing', models.CharField(max_length=10, verbose_name='Tracing')),
                ('date', models.DateField()),
                ('field_host', models.CharField(blank=True, max_length=50, verbose_name='Hostname/NºSerial')),
                ('ticket', models.CharField(blank=True, max_length=50, verbose_name='IM or RF')),
                ('comments', models.CharField(blank=True, max_length=100, verbose_name='Comments')),
            ],
            options={
                'verbose_name': 'Change control',
                'ordering': ['tracing'],
            },
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['id'], 'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventories'},
        ),
    ]
