# Generated by Django 3.0.8 on 2020-10-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20201025_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changecontrol',
            name='tracing',
            field=models.IntegerField(),
        ),
    ]
