# Generated by Django 3.0.8 on 2020-10-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20201025_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changecontrol',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
